[package]
name = "jaust"
version = "0.1.0"
authors = ["zwennesm <zwennesm@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.9.0"
rocket = "0.4.1"
redis = "0.10"
diesel = { version = "1.0.0", features = ["postgres"] }
harsh = "0.1.6"
rand = "0.6.5"
serde_json = "1.0"