version: '3'
services:
  app:
    image: jaust:0.1
    environment:
      - DATABASE_URL=redis://redis:6379
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data: