version: '3'
services:
  app:
    image: zwensman/jaust:0.0.3
    environment:
      - ROCKET_DIESEL_POSTGRES_POOL={ url = "postgres://postgres:password@db/jaust" }
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaust
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
